### ISSUE TITLE
Checksum Mismatch Error

### ISSUE THREAD

**Issue by brajchit** [101100/xbee-rx#19]
I found a error with v5.0, when send and receibe data from remote xbee:

```
/home/pi/Templates/gw-companyDemo-fincaDemo1/bluegateway/node_modules/xbee-api/lib/xbee-api.js:220
        var err = new Error("Checksum Mismatch " + JSON.stringify(S));
                  ^
Error: Checksum Mismatch {"buffer":{"type":"Buffer","data":[126,0,38,144,0,123,4,108,87,127,236,66,89,148,67,142,83,53,170,156,197,79,82,93,186,140,255,15,142,20,31,130,80,255,15,170,26,56,131,0,155,191,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},"offset":42,"length":38,"total":4061,"checksum":191,"b":191,"escape_next":false,"waiting":false}
    at XBeeAPI.parseRaw (/home/pi/Templates/gw-companyDemo-fincaDemo1/bluegateway/node_modules/xbee-api/lib/xbee-api.js:220:19)
    at Transform.XBeeAPI.parser._transform (/home/pi/Templates/gw-companyDemo-fincaDemo1/bluegateway/node_modules/xbee-api/lib/xbee-api.js:48:19)
    at Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:388:12)
    at Transform.Writable.write (node:internal/streams/writable:333:10)
    at SerialPort.ondata (node:internal/streams/readable:715:22)
    at SerialPort.emit (node:events:329:20)
    at addChunk (node:internal/streams/readable:304:12)
    at readableAddChunk (node:internal/streams/readable:279:9)
    at SerialPort.Readable.push (node:internal/streams/readable:218:10)
Emitted 'error' event on XBeeAPI instance at:
    at XBeeAPI.parseRaw (/home/pi/Templates/gw-companyDemo-fincaDemo1/bluegateway/node_modules/xbee-api/lib/xbee-api.js:221:14)
    at Transform.XBeeAPI.parser._transform (/home/pi/Templates/gw-companyDemo-fincaDemo1/bluegateway/node_modules/xbee-api/lib/xbee-api.js:48:19)
    [... lines matching original stack trace ...]
    at SerialPort.Readable.push (node:internal/streams/readable:218:10)
``` 

This occurs sometimes, when making requests in group(loop) to remote Xbees and they respond:
- Raspberry Pi OS (Linux v5.4)
- NVM v0.37.0
    - Nodejs v15.2.1
    - NPM v7.0.8

**Comment by 101100** [comment]
@brajchit Was this working on version 4?  It seems like the library might need to handle checksum errors more gracefully.
